=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/Condition.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/Condition",
  "description": "A clinical condition, problem, diagnosis, or other event, situation, issue, or clinical concept that has risen to a level of concern.",
  "type": "object",
  "required": ["resourceType", "subject"],
  "properties": {
    "resourceType": { "const": "Condition" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "clinicalStatus": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "verificationStatus": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "category": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "severity": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "code": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "bodySite": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "subject": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "encounter": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "onsetDateTime": { "type": "string" },
    "onsetAge": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" }, "system": { "type": "string" }, "code": { "type": "string" } } },
    "onsetPeriod": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "onsetRange": { "type": "object", "properties": { "low": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } }, "high": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } } } },
    "onsetString": { "type": "string" },
    "abatementDateTime": { "type": "string" },
    "abatementAge": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" }, "system": { "type": "string" }, "code": { "type": "string" } } },
    "abatementPeriod": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "abatementRange": { "type": "object", "properties": { "low": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } }, "high": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } } } },
    "abatementString": { "type": "string" },
    "recordedDate": { "type": "string" },
    "recorder": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "asserter": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "stage": { "type": "array", "items": { "type": "object", "properties": { "summary": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } }, "assessment": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } }, "type": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } } } },
    "evidence": { "type": "array", "items": { "type": "object", "properties": { "code": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } }, "detail": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } } } } },
    "note": { "type": "array", "items": { "type": "object", "properties": { "text": { "type": "string" }, "time": { "type": "string" }, "authorReference": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } }, "authorString": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/Condition-PFEIG-Condition-UndressingConcern.json
{
  "resourceType" : "Condition",
  "id" : "PFEIG-Condition-UndressingConcern",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-problems-health-concerns"]
  },
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition PFEIG-Condition-UndressingConcern</b></p><a name=\"PFEIG-Condition-UndressingConcern\"> </a><a name=\"hcPFEIG-Condition-UndressingConcern\"> </a><a name=\"PFEIG-Condition-UndressingConcern-en-US\"> </a><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://hl7.org/fhir/us/core/CodeSystem/condition-category health-concern}\">Health Concern</span>, <span title=\"Codes:{http://hl7.org/fhir/us/core/CodeSystem/us-core-category functional-status}\">Functional Status</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 284989005}\">Difficulty undressing (finding)</span></p><p><b>subject</b>: <a href=\"Patient-PFEIG-patientBSJ1.html\">Betsy Smith-Johnson Female, DoB Unknown ( http://example.org/identifiers/patient#10A3D58WH1600)</a></p><p><b>recordedDate</b>: 2024-01-18 14:10:00-0500</p><p><b>asserter</b>: <a href=\"Practitioner-PFEIG-Practitioner-JenCadbury.html\">Practitioner Jen Cadbury</a></p><p><b>note</b>: Betsy is frustrated, embarrassed, and worried about not being able to undress herself</p></div>"
  },
  "clinicalStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-clinical",
      "code" : "active"
    }]
  },
  "verificationStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
      "code" : "confirmed"
    }]
  },
  "category" : [{
    "coding" : [{
      "system" : "http://hl7.org/fhir/us/core/CodeSystem/condition-category",
      "code" : "health-concern",
      "display" : "Health Concern"
    }]
  },
  {
    "coding" : [{
      "system" : "http://hl7.org/fhir/us/core/CodeSystem/us-core-category",
      "code" : "functional-status",
      "display" : "Functional Status"
    }]
  }],
  "code" : {
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "284989005",
      "display" : "Difficulty undressing (finding)"
    }]
  },
  "subject" : {
    "reference" : "Patient/PFEIG-patientBSJ1"
  },
  "recordedDate" : "2024-01-18T14:10:00-05:00",
  "asserter" : {
    "reference" : "Practitioner/PFEIG-Practitioner-JenCadbury"
  },
  "note" : [{
    "text" : "Betsy is frustrated, embarrassed, and worried about not being able to undress herself"
  }]
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/Condition-PFEIG-Condition-AnemiaDiagnosis.json
{
  "resourceType" : "Condition",
  "id" : "PFEIG-Condition-AnemiaDiagnosis",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-encounter-diagnosis"]
  },
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition PFEIG-Condition-AnemiaDiagnosis</b></p><a name=\"PFEIG-Condition-AnemiaDiagnosis\"> </a><a name=\"hcPFEIG-Condition-AnemiaDiagnosis\"> </a><a name=\"PFEIG-Condition-AnemiaDiagnosis-en-US\"> </a><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category encounter-diagnosis}\">Encounter Diagnosis</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 691421000119108}\">Anemia co-occurrent and due to chronic kidney disease stage 3 (disorder)</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 113257007}\">Structure of cardiovascular system</span></p><p><b>subject</b>: <a href=\"Patient-PFEIG-patientBSJ1.html\">Betsy Smith-Johnson Female, DoB Unknown ( http://example.org/identifiers/patient#10A3D58WH1600)</a></p><p><b>recordedDate</b>: 2024-06-23 13:15:00-0400</p><p><b>note</b>: See lab</p></div>"
  },
  "extension" : [{
    "url" : "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
    "valueDateTime" : "2024-06-23T13:15:00-04:00"
  }],
  "clinicalStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-clinical",
      "code" : "active"
    }]
  },
  "verificationStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
      "code" : "confirmed"
    }]
  },
  "category" : [{
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-category",
      "code" : "encounter-diagnosis",
      "display" : "Encounter Diagnosis"
    }]
  }],
  "code" : {
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "691421000119108",
      "display" : "Anemia co-occurrent and due to chronic kidney disease stage 3 (disorder)"
    }]
  },
  "bodySite" : [{
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "113257007",
      "display" : "Structure of cardiovascular system"
    }]
  }],
  "subject" : {
    "reference" : "Patient/PFEIG-patientBSJ1"
  },
  "recordedDate" : "2024-06-23T13:15:00-04:00",
  "note" : [{
    "text" : "See lab"
  }]
}

=== node-on-fhir/core/packages/pacio-core/data/connectathon-july-2026-examples/Condition-VioletGartner01-condition-RightFemurBreak-01.json
{
  "resourceType": "Condition",
  "id": "VioletGartner01-condition-RightFemurBreak-01",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-encounter-diagnosis"
    ]
  },
  "text": {
    "status": "extensions",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition VioletGartner01-condition-RightFemurBreak-01</b></p><a name=\"VioletGartner01-condition-RightFemurBreak-01\"> </a><a name=\"hcVioletGartner01-condition-RightFemurBreak-01\"> </a><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\"/><p style=\"margin-bottom: 0px\">Profile: <a href=\"http://hl7.org/fhir/us/core/STU6.1/StructureDefinition-us-core-condition-encounter-diagnosis.html\">US Core Condition Encounter Diagnosis Profile</a></p></div><p><b>Condition Asserted Date</b>: 2026-01-10 15:40:00-0500</p><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category encounter-diagnosis}\">Encounter Diagnosis</span></p><p><b>code</b>: <span title=\"Codes:{http://hl7.org/fhir/sid/icd-10-cm S72.421}\">Right femur break</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 737450007}\">Structure of lateral condyle of right femur (body structure)</span></p><p><b>subject</b>: <a href=\"Patient-patient-VioletGartner01.html\">Violet Gartner</a></p><p><b>recordedDate</b>: 2026-01-10 15:40:00-0500</p><p><b>asserter</b>: <a href=\"PractitionerRole-PractitionerRole-Physician-PriyaSarkar.html\">PractitionerRole Emergency Medicine Physician</a></p></div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
      "valueDateTime": "2026-01-10T15:40:00-05:00"
    }
  ],
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "active"
      }
    ]
  },
  "verificationStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code": "confirmed"
      }
    ]
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://hl7.org/fhir/sid/icd-10-cm",
        "code": "S72.421",
        "display": "Displaced fracture of lateral condyle of right femur"
      }
    ],
    "text": "Right femur break"
  },
  "bodySite": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "737450007",
          "display": "Structure of lateral condyle of right femur (body structure)"
        }
      ],
      "text": "Structure of lateral condyle of right femur (body structure)"
    }
  ],
  "subject": {
    "reference": "Patient/patient-VioletGartner01",
    "display": "Violet Gartner"
  },
  "recordedDate": "2026-01-10T15:40:00-05:00",
  "asserter": {
    "reference": "PractitionerRole/PractitionerRole-Physician-PriyaSarkar"
  }
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/Condition-betsysmith-johnson01-Condition-Stroke-01.json
{
  "resourceType": "Condition",
  "id": "betsysmith-johnson01-Condition-Stroke-01",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-encounter-diagnosis"
    ]
  },
  "text": {
    "status": "extensions",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition betsysmith-johnson01-Condition-Stroke-01</b></p><a name=\"betsysmith-johnson01-Condition-Stroke-01\"> </a><a name=\"hcbetsysmith-johnson01-Condition-Stroke-01\"> </a><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\"/><p style=\"margin-bottom: 0px\">Profile: <a href=\"http://hl7.org/fhir/us/pacio-pfe/STU2/StructureDefinition-pfe-condition-encounter-diagnosis.html\">Personal Functioning and Engagement Condition Encounter Diagnosis Profile</a></p></div><p><b>Condition Asserted Date</b>: 2025-05-03 15:30:00-0400</p><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://hl7.org/fhir/sid/icf s11009}\">Structure of cortical lobes, unspecified</span>, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category encounter-diagnosis}\">Encounter Diagnosis</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 422504002}\">Ischemic Stroke (disorder)</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 414722000}\">Structure of middle cerebral artery M1 segment</span>, <span title=\"Codes:{http://snomed.info/sct 7771000}\">Left</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>onset</b>: 2025-05-03 11:30:00-0400</p><p><b>recordedDate</b>: 2025-05-03 15:30:00-0400</p><p><b>asserter</b>: <a href=\"PractitionerRole-PractitionerRole-Neuro-DavidAlbahari.html\">PractitionerRole Neurology Physician</a></p><p><b>note</b>: </p><blockquote><div><p>Partial occlusion of MCA. Stroke event witnessed. EMS response / patient arrived within 45 minutes of symptom onset. Verified by CT with contrast. tPA administered within 2 hours of symptom onset.</p>\n</div></blockquote></div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
      "valueDateTime": "2025-05-03T15:30:00-04:00"
    }
  ],
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "active"
      }
    ]
  },
  "verificationStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code": "confirmed"
      }
    ]
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/sid/icf",
          "code": "s11009",
          "display": "Structure of cortical lobes, unspecified"
        }
      ]
    },
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "422504002",
        "display": "Ischemic stroke"
      }
    ],
    "text": "Ischemic Stroke (disorder)"
  },
  "bodySite": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "414722000",
          "display": "Structure of middle cerebral artery M1 segment"
        }
      ]
    },
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "7771000",
          "display": "Left"
        }
      ]
    }
  ],
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "onsetDateTime": "2025-05-03T11:30:00-04:00",
  "recordedDate": "2025-05-03T15:30:00-04:00",
  "asserter": {
    "reference": "PractitionerRole/PractitionerRole-Neuro-DavidAlbahari"
  },
  "note": [
    {
      "text": "Partial occlusion of MCA. Stroke event witnessed. EMS response / patient arrived within 45 minutes of symptom onset. Verified by CT with contrast. tPA administered within 2 hours of symptom onset."
    }
  ]
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/Condition-betsysmith-johnson01-Condition-NauseaAndVomiting-01.json
{
  "resourceType": "Condition",
  "id": "betsysmith-johnson01-Condition-NauseaAndVomiting-01",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-encounter-diagnosis"
    ]
  },
  "text": {
    "status": "extensions",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition betsysmith-johnson01-Condition-NauseaAndVomiting-01</b></p><a name=\"betsysmith-johnson01-Condition-NauseaAndVomiting-01\"> </a><a name=\"hcbetsysmith-johnson01-Condition-NauseaAndVomiting-01\"> </a><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\"/><p style=\"margin-bottom: 0px\">Profile: <a href=\"http://hl7.org/fhir/us/pacio-pfe/STU2/StructureDefinition-pfe-condition-encounter-diagnosis.html\">Personal Functioning and Engagement Condition Encounter Diagnosis Profile</a></p></div><p><b>Condition Asserted Date</b>: 2024-08-22 16:30:00-0400</p><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://hl7.org/fhir/sid/icf b5350}\">Sensation of nausea</span>, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category encounter-diagnosis}\">Encounter Diagnosis</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 16932000}\">Nausea and Vomiting (disorder)</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>onset</b>: 2024-08-22 16:30:00-0400</p><p><b>recordedDate</b>: 2024-08-22 16:30:00-0400</p><p><b>note</b>: </p><blockquote><div><p>Patient pressed call button for vomiting. She reports she started feeling nauseated about ten minutes ago.</p>\n</div></blockquote></div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
      "valueDateTime": "2024-08-22T16:30:00-04:00"
    }
  ],
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "active"
      }
    ]
  },
  "verificationStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code": "confirmed"
      }
    ]
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/sid/icf",
          "code": "b5350",
          "display": "Sensation of nausea"
        }
      ]
    },
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "16932000",
        "display": "Nausea and vomiting"
      }
    ],
    "text": "Nausea and Vomiting (disorder)"
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "onsetDateTime": "2024-08-22T16:30:00-04:00",
  "recordedDate": "2024-08-22T16:30:00-04:00",
  "note": [
    {
      "text": "Patient pressed call button for vomiting. She reports she started feeling nauseated about ten minutes ago."
    }
  ]
}
