=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/Condition.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/Condition",
  "description": "A clinical condition, problem, diagnosis, or other event, situation, issue, or clinical concept that has risen to a level of concern.",
  "type": "object",
  "required": ["resourceType", "subject"],
  "properties": {
    "resourceType": { "const": "Condition" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "clinicalStatus": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "verificationStatus": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "category": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "severity": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "code": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "bodySite": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "subject": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "encounter": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "onsetDateTime": { "type": "string" },
    "onsetAge": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" }, "system": { "type": "string" }, "code": { "type": "string" } } },
    "onsetPeriod": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "onsetRange": { "type": "object", "properties": { "low": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } }, "high": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } } } },
    "onsetString": { "type": "string" },
    "abatementDateTime": { "type": "string" },
    "abatementAge": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" }, "system": { "type": "string" }, "code": { "type": "string" } } },
    "abatementPeriod": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "abatementRange": { "type": "object", "properties": { "low": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } }, "high": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" } } } } },
    "abatementString": { "type": "string" },
    "recordedDate": { "type": "string" },
    "recorder": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "asserter": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "stage": { "type": "array", "items": { "type": "object", "properties": { "summary": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } }, "assessment": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } }, "type": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } } } },
    "evidence": { "type": "array", "items": { "type": "object", "properties": { "code": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } }, "detail": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } } } } },
    "note": { "type": "array", "items": { "type": "object", "properties": { "text": { "type": "string" }, "time": { "type": "string" }, "authorReference": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } }, "authorString": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/Condition-betsysmith-johnson01-Condition-OTProblemListRightWeak-01.json
{
  "resourceType": "Condition",
  "id": "betsysmith-johnson01-Condition-OTProblemListRightWeak-01",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-problems-health-concerns"
    ]
  },
  "text": {
    "status": "extensions",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition betsysmith-johnson01-Condition-OTProblemListRightWeak-01</b></p><a name=\"betsysmith-johnson01-Condition-OTProblemListRightWeak-01\"> </a><a name=\"hcbetsysmith-johnson01-Condition-OTProblemListRightWeak-01\"> </a><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\"/><p style=\"margin-bottom: 0px\">Profile: <a href=\"http://hl7.org/fhir/us/pacio-pfe/STU2/StructureDefinition-pfe-condition-problems-health-concerns.html\">Personal Functioning and Engagement Condition Problems and Health Concerns Profile</a></p></div><p><b>Condition Asserted Date</b>: 2025-05-03 14:40:00-0400</p><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://hl7.org/fhir/sid/icf b7301}\">Power of muscles of one limb</span>, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category problem-list-item}\">Problem List Item</span>, <span title=\"Codes:{http://hl7.org/fhir/us/core/CodeSystem/us-core-category functional-status}\">Functional Status</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 570961000124101}\">Weakness of right upper limb (finding)</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 368209003}\">Entire Right Arm</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>recordedDate</b>: 2025-05-03 14:40:00-0400</p><p><b>asserter</b>: <a href=\"PractitionerRole-PractitionerRole-PT-DeyonteDarden.html\">PractitionerRole Physical Therapist</a></p><h3>Evidences</h3><table class=\"grid\"><tr><td style=\"display: none\">-</td><td><b>Detail</b></td></tr><tr><td style=\"display: none\">*</td><td><a href=\"Condition-betsysmith-johnson01-Condition-Hemiparesis-01.html\">Condition Monoplegia of upper limb affecting right dominant side</a></td></tr></table><p><b>note</b>: </p><blockquote><div><p>The weakness and lack of coordination in the patient's right shoulder, arm, and hand are secondary to the stroke. PT/OT from SNF report improvements to rotator cuff strength over last month.</p>\n</div></blockquote></div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
      "valueDateTime": "2025-05-03T14:40:00-04:00"
    }
  ],
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "active"
      }
    ]
  },
  "verificationStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code": "confirmed"
      }
    ]
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/sid/icf",
          "code": "b7301",
          "display": "Power of muscles of one limb"
        }
      ]
    },
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "problem-list-item",
          "display": "Problem List Item"
        }
      ]
    },
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-category",
          "code": "functional-status",
          "display": "Functional Status"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "version": "http://snomed.info/sct/731000124108",
        "code": "570961000124101",
        "display": "Weakness of right upper limb (finding)"
      }
    ],
    "text": "Weakness of right upper limb (finding)"
  },
  "bodySite": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "368209003",
          "display": "Right upper arm"
        }
      ],
      "text": "Entire Right Arm"
    }
  ],
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "recordedDate": "2025-05-03T14:40:00-04:00",
  "asserter": {
    "reference": "PractitionerRole/PractitionerRole-PT-DeyonteDarden"
  },
  "evidence": [
    {
      "detail": [
        {
          "reference": "Condition/betsysmith-johnson01-Condition-Hemiparesis-01"
        }
      ]
    }
  ],
  "note": [
    {
      "text": "The weakness and lack of coordination in the patient's right shoulder, arm, and hand are secondary to the stroke. PT/OT from SNF report improvements to rotator cuff strength over last month."
    }
  ]
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/Condition-PFEIG-Condition-RightWeak.json
{
  "resourceType" : "Condition",
  "id" : "PFEIG-Condition-RightWeak",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-problems-health-concerns"]
  },
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition PFEIG-Condition-RightWeak</b></p><a name=\"PFEIG-Condition-RightWeak\"> </a><a name=\"hcPFEIG-Condition-RightWeak\"> </a><a name=\"PFEIG-Condition-RightWeak-en-US\"> </a><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://hl7.org/fhir/us/core/CodeSystem/condition-category health-concern}\">Health Concern</span>, <span title=\"Codes:{http://hl7.org/fhir/us/core/CodeSystem/us-core-category functional-status}\">Functional Status</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 570961000124101}\">Weakness of right upper limb (finding)</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 368209003}\">Right upper arm structure (body structure)</span></p><p><b>subject</b>: <a href=\"Patient-PFEIG-patientBSJ1.html\">Betsy Smith-Johnson Female, DoB Unknown ( http://example.org/identifiers/patient#10A3D58WH1600)</a></p><p><b>onset</b>: 2023-12-15 15:40:00-0500</p><p><b>recordedDate</b>: 2024-01-18 14:10:00-0500</p><p><b>asserter</b>: <a href=\"Practitioner-PFEIG-Practitioner-JenCadbury.html\">Practitioner Jen Cadbury</a></p><h3>Evidences</h3><table class=\"grid\"><tr><td style=\"display: none\">-</td><td><b>Detail</b></td></tr><tr><td style=\"display: none\">*</td><td><a href=\"Condition-PFEIG-Condition-HemiparesisDiagnosis.html\">Condition Right hemiparesis (disorder)</a></td></tr></table><p><b>note</b>: The weakness and lack of coordination in the patient's right shoulder, arm, and hand are secondary to the stroke. PT/OT from SNF report improvements to rotator cuff strength over last month.</p></div>"
  },
  "extension" : [{
    "url" : "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
    "valueDateTime" : "2023-12-16T13:30:00-05:00"
  }],
  "clinicalStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-clinical",
      "code" : "active"
    }]
  },
  "verificationStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
      "code" : "confirmed"
    }]
  },
  "category" : [{
    "coding" : [{
      "system" : "http://hl7.org/fhir/us/core/CodeSystem/condition-category",
      "code" : "health-concern",
      "display" : "Health Concern"
    }]
  },
  {
    "coding" : [{
      "system" : "http://hl7.org/fhir/us/core/CodeSystem/us-core-category",
      "code" : "functional-status",
      "display" : "Functional Status"
    }]
  }],
  "code" : {
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "570961000124101",
      "display" : "Weakness of right upper limb (finding)"
    }]
  },
  "bodySite" : [{
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "368209003",
      "display" : "Right upper arm structure (body structure)"
    }]
  }],
  "subject" : {
    "reference" : "Patient/PFEIG-patientBSJ1"
  },
  "onsetDateTime" : "2023-12-15T15:40:00-05:00",
  "recordedDate" : "2024-01-18T14:10:00-05:00",
  "asserter" : {
    "reference" : "Practitioner/PFEIG-Practitioner-JenCadbury"
  },
  "evidence" : [{
    "detail" : [{
      "reference" : "Condition/PFEIG-Condition-HemiparesisDiagnosis"
    }]
  }],
  "note" : [{
    "text" : "The weakness and lack of coordination in the patient's right shoulder, arm, and hand are secondary to the stroke. PT/OT from SNF report improvements to rotator cuff strength over last month."
  }]
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/Condition-PFEIG-Condition-HemiparesisDiagnosis.json
{
  "resourceType" : "Condition",
  "id" : "PFEIG-Condition-HemiparesisDiagnosis",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-encounter-diagnosis"]
  },
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition PFEIG-Condition-HemiparesisDiagnosis</b></p><a name=\"PFEIG-Condition-HemiparesisDiagnosis\"> </a><a name=\"hcPFEIG-Condition-HemiparesisDiagnosis\"> </a><a name=\"PFEIG-Condition-HemiparesisDiagnosis-en-US\"> </a><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category encounter-diagnosis}\">Encounter Diagnosis</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 278286009}\">Right hemiparesis (disorder)</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 368209003}\">Right upper arm structure (body structure)</span></p><p><b>subject</b>: <a href=\"Patient-PFEIG-patientBSJ1.html\">Betsy Smith-Johnson Female, DoB Unknown ( http://example.org/identifiers/patient#10A3D58WH1600)</a></p><p><b>onset</b>: 2023-12-15 15:40:00-0500</p><p><b>recordedDate</b>: 2023-12-16 13:30:00-0500</p><p><b>note</b>: Patient began experiencing right sided weakness, primarily in arm and shoulder. There was no facial droop, but patient reports &quot;tingling&quot; in R face / numbness along R brow. Symptoms in face resolved post tPA administration. Strength improved in shoulder, weakness did not fully resolve. Demonstrates R arm weakness and lack of coordination. Fine motor skills significantly degraded and have not improved post tPA.</p></div>"
  },
  "extension" : [{
    "url" : "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
    "valueDateTime" : "2023-12-16T13:30:00-05:00"
  }],
  "clinicalStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-clinical",
      "code" : "active"
    }]
  },
  "verificationStatus" : {
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
      "code" : "confirmed"
    }]
  },
  "category" : [{
    "coding" : [{
      "system" : "http://terminology.hl7.org/CodeSystem/condition-category",
      "code" : "encounter-diagnosis",
      "display" : "Encounter Diagnosis"
    }]
  }],
  "code" : {
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "278286009",
      "display" : "Right hemiparesis (disorder)"
    }]
  },
  "bodySite" : [{
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "368209003",
      "display" : "Right upper arm structure (body structure)"
    }]
  }],
  "subject" : {
    "reference" : "Patient/PFEIG-patientBSJ1"
  },
  "onsetDateTime" : "2023-12-15T15:40:00-05:00",
  "recordedDate" : "2023-12-16T13:30:00-05:00",
  "note" : [{
    "text" : "Patient began experiencing right sided weakness, primarily in arm and shoulder. There was no facial droop, but patient reports \"tingling\" in R face / numbness along R brow. Symptoms in face resolved post tPA administration. Strength improved in shoulder, weakness did not fully resolve. Demonstrates R arm weakness and lack of coordination. Fine motor skills significantly degraded and have not improved post tPA."
  }]
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/Condition-betsysmith-johnson01-Condition-OTProblemListDecondition-01.json
{
  "resourceType": "Condition",
  "id": "betsysmith-johnson01-Condition-OTProblemListDecondition-01",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-condition-problems-health-concerns"
    ]
  },
  "text": {
    "status": "extensions",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition betsysmith-johnson01-Condition-OTProblemListDecondition-01</b></p><a name=\"betsysmith-johnson01-Condition-OTProblemListDecondition-01\"> </a><a name=\"hcbetsysmith-johnson01-Condition-OTProblemListDecondition-01\"> </a><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\"/><p style=\"margin-bottom: 0px\">Profile: <a href=\"http://hl7.org/fhir/us/pacio-pfe/STU2/StructureDefinition-pfe-condition-problems-health-concerns.html\">Personal Functioning and Engagement Condition Problems and Health Concerns Profile</a></p></div><p><b>Condition Asserted Date</b>: 2024-09-03 15:40:00-0400</p><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://hl7.org/fhir/sid/icf b7303}\">Power of muscles in lower half of the body</span>, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category problem-list-item}\">Problem List Item</span>, <span title=\"Codes:{http://hl7.org/fhir/us/core/CodeSystem/us-core-category functional-status}\">Functional Status</span></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 31031000119102}\">Physical deconditioning (finding)</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 362875007}\">Entire lower body</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>onset</b>: 2024-08-30 15:40:00-0400</p><p><b>recordedDate</b>: 2024-09-03 15:40:00-0400</p><p><b>asserter</b>: <a href=\"PractitionerRole-Role-OT-JenCadbury.html\">PractitionerRole Occupational Therapist</a></p><blockquote><p><b>evidence</b></p><p><b>detail</b>: <a href=\"Observation-betsysmith-johnson01-MDS-ShortWalk1.html\">Observation Walk 50 feet with two turns - functional goal during assessment period [CMS Assessment]</a></p></blockquote><blockquote><p><b>evidence</b></p><p><b>detail</b>: <a href=\"Observation-betsysmith-johnson01-MDS-SitStand1.html\">Observation Sit to stand - functional goal during assessment period [CMS Assessment]</a></p></blockquote><blockquote><p><b>evidence</b></p><p><b>detail</b>: <a href=\"Observation-betsysmith-johnson01-MDS-SitUp1.html\">Observation Lying to sitting on side of bed - functional goal during assessment period [CMS Assessment]</a></p></blockquote><p><b>note</b>: </p><blockquote><div><p>The weakness in the patient's lower extremities is secondary to deconditioning. According to the report from Neurology, patient did not have motor or sensory deficits below upper chest. High rehab potential.</p>\n</div></blockquote></div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
      "valueDateTime": "2024-09-03T15:40:00-04:00"
    }
  ],
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "active"
      }
    ]
  },
  "verificationStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code": "confirmed"
      }
    ]
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/sid/icf",
          "code": "b7303",
          "display": "Power of muscles in lower half of the body"
        }
      ]
    },
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "problem-list-item",
          "display": "Problem List Item"
        }
      ]
    },
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-category",
          "code": "functional-status",
          "display": "Functional Status"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "31031000119102",
        "display": "Physical deconditioning"
      }
    ],
    "text": "Physical deconditioning (finding)"
  },
  "bodySite": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "362875007",
          "display": "Entire lower body"
        }
      ]
    }
  ],
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "onsetDateTime": "2024-08-30T15:40:00-04:00",
  "recordedDate": "2024-09-03T15:40:00-04:00",
  "asserter": {
    "reference": "PractitionerRole/Role-OT-JenCadbury"
  },
  "evidence": [
    {
      "detail": [
        {
          "reference": "Observation/betsysmith-johnson01-MDS-ShortWalk1"
        }
      ]
    },
    {
      "detail": [
        {
          "reference": "Observation/betsysmith-johnson01-MDS-SitStand1"
        }
      ]
    },
    {
      "detail": [
        {
          "reference": "Observation/betsysmith-johnson01-MDS-SitUp1"
        }
      ]
    }
  ],
  "note": [
    {
      "text": "The weakness in the patient's lower extremities is secondary to deconditioning. According to the report from Neurology, patient did not have motor or sensory deficits below upper chest. High rehab potential."
    }
  ]
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/Condition-VioletGartner01-condition-RightArmPain-01.json
{
  "resourceType": "Condition",
  "id": "VioletGartner01-condition-RightArmPain-01",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-encounter-diagnosis"
    ]
  },
  "text": {
    "status": "extensions",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Condition VioletGartner01-condition-RightArmPain-01</b></p><a name=\"VioletGartner01-condition-RightArmPain-01\"> </a><a name=\"hcVioletGartner01-condition-RightArmPain-01\"> </a><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\"/><p style=\"margin-bottom: 0px\">Profile: <a href=\"http://hl7.org/fhir/us/core/STU6.1/StructureDefinition-us-core-condition-encounter-diagnosis.html\">US Core Condition Encounter Diagnosis Profile</a></p></div><p><b>Condition Asserted Date</b>: 2026-01-10 15:40:00-0500</p><p><b>clinicalStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-clinical active}\">Active</span></p><p><b>verificationStatus</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-ver-status confirmed}\">Confirmed</span></p><p><b>category</b>: <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/condition-category encounter-diagnosis}\">Encounter Diagnosis</span></p><p><b>code</b>: <span title=\"Codes:{http://hl7.org/fhir/sid/icd-10-cm M79.601}\">Right arm pain</span></p><p><b>bodySite</b>: <span title=\"Codes:{http://snomed.info/sct 368209003}\">Right upper arm structure (body structure)</span></p><p><b>subject</b>: <a href=\"Patient-patient-VioletGartner01.html\">Violet Gartner</a></p><p><b>recordedDate</b>: 2026-01-10 15:40:00-0500</p><p><b>asserter</b>: <a href=\"PractitionerRole-PractitionerRole-Physician-PriyaSarkar.html\">PractitionerRole Emergency Medicine Physician</a></p></div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/condition-assertedDate",
      "valueDateTime": "2026-01-10T15:40:00-05:00"
    }
  ],
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "active"
      }
    ]
  },
  "verificationStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code": "confirmed"
      }
    ]
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://hl7.org/fhir/sid/icd-10-cm",
        "code": "M79.601",
        "display": "Pain in right arm"
      }
    ],
    "text": "Right arm pain"
  },
  "bodySite": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "368209003",
          "display": "Right upper arm structure (body structure)"
        }
      ],
      "text": "Right upper arm structure (body structure)"
    }
  ],
  "subject": {
    "reference": "Patient/patient-VioletGartner01",
    "display": "Violet Gartner"
  },
  "recordedDate": "2026-01-10T15:40:00-05:00",
  "asserter": {
    "reference": "PractitionerRole/PractitionerRole-Physician-PriyaSarkar"
  }
}
