=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/DeviceUseStatement.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/DeviceUseStatement",
  "description": "A record of a device being used by a patient where the record is the result of a report from the patient or another clinician.",
  "type": "object",
  "required": ["resourceType", "status", "subject", "device"],
  "properties": {
    "resourceType": { "const": "DeviceUseStatement" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "basedOn": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "status": { "type": "string", "enum": ["active", "completed", "entered-in-error", "intended", "stopped", "on-hold"] },
    "subject": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "derivedFrom": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "timingTiming": { "type": "object" },
    "timingPeriod": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "timingDateTime": { "type": "string" },
    "recordedOn": { "type": "string" },
    "source": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "device": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "reasonCode": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "reasonReference": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "bodySite": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "note": { "type": "array", "items": { "type": "object", "properties": { "authorReference": { "type": "object" }, "authorString": { "type": "string" }, "time": { "type": "string" }, "text": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/DeviceUseStatement-PFEIG-FSC-Hospital-Discharge-Mobility-1-UseOfDevice-3.json
{
  "resourceType" : "DeviceUseStatement",
  "id" : "PFEIG-FSC-Hospital-Discharge-Mobility-1-UseOfDevice-3",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-use-of-device"]
  },
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: DeviceUseStatement PFEIG-FSC-Hospital-Discharge-Mobility-1-UseOfDevice-3</b></p><a name=\"PFEIG-FSC-Hospital-Discharge-Mobility-1-UseOfDevice-3\"> </a><a name=\"hcPFEIG-FSC-Hospital-Discharge-Mobility-1-UseOfDevice-3\"> </a><a name=\"PFEIG-FSC-Hospital-Discharge-Mobility-1-UseOfDevice-3-en-US\"> </a><p><b>status</b>: Active</p><p><b>subject</b>: <a href=\"Patient-PFEIG-patientBSJ1.html\">Betsy Smith-Johnson Female, DoB Unknown ( http://example.org/identifiers/patient#10A3D58WH1600)</a></p><p><b>derivedFrom</b>: <a href=\"Observation-PFEIG-FSC-Hospital-Discharge-Mobility-1.html\">Observation Mobility - discharge performance during 3 day assessment period [CMS Assessment]</a></p><p><b>recordedOn</b>: 2020-07-10 14:34:00-0500</p><p><b>source</b>: <a href=\"Practitioner-PFEIG-Practitioner-RonMarble.html\">Practitioner Ron Marble</a></p><p><b>device</b>: <a href=\"Device-PFEIG-CMS-Device-Walker.html\">Device</a></p></div>"
  },
  "status" : "active",
  "subject" : {
    "reference" : "Patient/PFEIG-patientBSJ1"
  },
  "derivedFrom" : [{
    "reference" : "Observation/PFEIG-FSC-Hospital-Discharge-Mobility-1"
  }],
  "recordedOn" : "2020-07-10T14:34:00-05:00",
  "source" : {
    "reference" : "Practitioner/PFEIG-Practitioner-RonMarble"
  },
  "device" : {
    "reference" : "Device/PFEIG-CMS-Device-Walker"
  }
}
