=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/DiagnosticReport.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/DiagnosticReport",
  "description": "The findings and interpretation of diagnostic tests performed on patients, groups of patients, devices, and locations, and/or specimens derived from these. The report includes clinical context such as requesting and provider information, and some mix of atomic results, images, textual and coded interpretations, and formatted representation of diagnostic reports.",
  "type": "object",
  "required": ["resourceType", "code"],
  "properties": {
    "resourceType": { "const": "DiagnosticReport" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "basedOn": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "status": { "type": "string", "enum": ["registered", "partial", "preliminary", "final", "amended", "corrected", "appended", "cancelled", "entered-in-error", "unknown"] },
    "category": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "code": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "subject": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "encounter": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "effectiveDateTime": { "type": "string" },
    "effectivePeriod": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "issued": { "type": "string" },
    "performer": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "resultsInterpreter": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "specimen": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "result": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "imagingStudy": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "media": { "type": "array", "items": { "type": "object", "properties": { "comment": { "type": "string" }, "link": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } } } },
    "conclusion": { "type": "string" },
    "conclusionCode": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "presentedForm": { "type": "array", "items": { "type": "object", "properties": { "contentType": { "type": "string" }, "language": { "type": "string" }, "data": { "type": "string" }, "url": { "type": "string" }, "size": { "type": "integer" }, "hash": { "type": "string" }, "title": { "type": "string" }, "creation": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/DiagnosticReport-PFEIG-Narrative-History-Functional-Status-1.json
{
  "resourceType" : "DiagnosticReport",
  "id" : "PFEIG-Narrative-History-Functional-Status-1",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/pfe-narrative-history-of-status"]
  },
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: DiagnosticReport PFEIG-Narrative-History-Functional-Status-1</b></p><a name=\"PFEIG-Narrative-History-Functional-Status-1\"> </a><a name=\"hcPFEIG-Narrative-History-Functional-Status-1\"> </a><a name=\"PFEIG-Narrative-History-Functional-Status-1-en-US\"> </a><h2><span title=\"Codes:{http://loinc.org 10158-4}\">History of Functional status Narrative</span> (<span title=\"Codes:{http://loinc.org LP7839-6}\">Pathology</span>, <span title=\"Codes:{http://hl7.org/fhir/us/pacio-pfe/CodeSystem/pfe-category-cs BlockL2-d41}\">Mobility</span>, <span title=\"Codes:{http://hl7.org/fhir/us/pacio-pfe/CodeSystem/pfe-category-cs BlockL2-d51}\">Self-care</span>) </h2><table class=\"grid\"><tr><td>Subject</td><td>Betsy Smith-Johnson Female, DoB Unknown ( http://example.org/identifiers/patient#10A3D58WH1600)</td></tr><tr><td>When For</td><td>2019-07-01 --&gt; 2020-11-30</td></tr><tr><td>Performer</td><td> <a href=\"PractitionerRole-PFEIG-provider-role-pcp.html\">PractitionerRole Primary Care Clinic/Center</a></td></tr></table><p><b>Report Details</b></p></div>"
  },
  "extension" : [{
    "url" : "http://hl7.org/fhir/StructureDefinition/event-location",
    "valueReference" : {
      "reference" : "Location/PFEIG-provider-org-loc-01"
    }
  },
  {
    "url" : "http://hl7.org/fhir/us/pacio-pfe/StructureDefinition/assistance-required",
    "valueCodeableConcept" : {
      "coding" : [{
        "system" : "http://loinc.org",
        "code" : "LA11539-6",
        "display" : "Independent - Patient completed all the activities by themself, with or without an assistive device, with no assistance from a helper."
      }]
    }
  }],
  "status" : "final",
  "category" : [{
    "coding" : [{
      "system" : "http://loinc.org",
      "code" : "LP7839-6",
      "display" : "Pathology"
    }]
  },
  {
    "coding" : [{
      "system" : "http://hl7.org/fhir/us/pacio-pfe/CodeSystem/pfe-category-cs",
      "code" : "BlockL2-d41",
      "display" : "Mobility"
    }]
  },
  {
    "coding" : [{
      "system" : "http://hl7.org/fhir/us/pacio-pfe/CodeSystem/pfe-category-cs",
      "code" : "BlockL2-d51",
      "display" : "Self-care"
    }]
  }],
  "code" : {
    "coding" : [{
      "system" : "http://loinc.org",
      "code" : "10158-4",
      "display" : "History of Functional status Narrative"
    }]
  },
  "subject" : {
    "reference" : "Patient/PFEIG-patientBSJ1"
  },
  "effectivePeriod" : {
    "start" : "2019-07-01",
    "end" : "2020-11-30"
  },
  "performer" : [{
    "reference" : "PractitionerRole/PFEIG-provider-role-pcp"
  }],
  "presentedForm" : [{
    "contentType" : "text/plain",
    "data" : "UHJpb3IgdG8gdGhlIGN1cnJlbnQgYWRtaXNzaW9uLCBwYXRpZW50IHdhcyBhIGNvbW11bml0eSBhbWJ1bGF0b3IsIGFibGUgdG8gYXR0ZW5kIGRlc2lyZWQgYWN0aXZpdGVzIGFuZCBjYXJlIGZvciBoZXJzZWxmIGluZGVwZW5kZW50bHku"
  }]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/2026-07-cms-connectathon/BetsySmithJohnson/fhir/DiagnosticReport-betsysmith-johnson01-diagnosticReport-coag-01.json
{
  "resourceType": "DiagnosticReport",
  "id": "betsysmith-johnson01-diagnosticReport-coag-01",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: DiagnosticReport betsysmith-johnson01-diagnosticReport-coag-01</b></p><a name=\"betsysmith-johnson01-diagnosticReport-coag-01\"> </a><a name=\"hcbetsysmith-johnson01-diagnosticReport-coag-01\"> </a><h2><span title=\"Codes:{http://loinc.org 57021-8}\">Coagulation Panel</span> (<span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v2-0074 LAB}\">Laboratory</span>) </h2><table class=\"grid\"><tr><td>Subject</td><td>Smith-Johnson, Betsy Female, DoB: 1950-11-15 ( http://hl7.org/fhir/sid/us-medicare#United States Medicare Number#1PA3D58WH16)</td></tr><tr><td>When For</td><td>2025-05-03 08:30:00+1100</td></tr><tr><td>Performer</td><td> <a href=\"Organization-org-ED-Metro-Hospital.html\">Organization Metro Hospital Emergency Department</a></td></tr></table><p><b>Report Details</b></p><table class=\"grid\"><tr><td><b>Code</b></td><td><b>Value</b></td><td><b>Reference Range</b></td><td><b>Flags</b></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-pt-coag-panel.html\"><span title=\"Codes:{http://loinc.org 5902-2}\">Prothrombin time</span></a></td><td>13.2 s<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codes = 's')</span></td><td>11 s - 13 s</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation H}\">High</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-inr-coag-panel.html\"><span title=\"Codes:{http://loinc.org 6301-6}\">INR in Platelet poor plasma by Coagulation assay</span></a></td><td>1.1 ratio<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  code1 = '1')</span></td><td>0.9 ratio - 1.1 ratio</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-aptt-coag-panel.html\"><span title=\"Codes:{http://loinc.org 3173-2}\">aPTT in Blood by Coagulation assay</span></a></td><td>28.5 s<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codes = 's')</span></td><td>25 s - 35 s</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-ddimer-coag-panel.html\"><span title=\"Codes:{http://loinc.org 48065-7}\">Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma</span></a></td><td>1.8 mg/L<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codemg/L = 'mg/L')</span></td><td>&lt;0.5 mg/L</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation H}\">High</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-platelet-coag-panel.html\"><span title=\"Codes:{http://loinc.org 777-3}\">Platelets [#/volume] in Blood by Automated count</span></a></td><td>285 10*3/uL<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  code10*3/uL = '10*3/uL')</span></td><td>150 10*3/uL - 400 10*3/uL</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-thrombin-time-coag-panel.html\"><span title=\"Codes:{http://loinc.org 3243-3}\">Thrombin time</span></a></td><td>16.8 s<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codes = 's')</span></td><td>14 s - 18 s</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-factor-viii-coag-panel.html\"><span title=\"Codes:{http://loinc.org 3209-4}\">Coagulation factor VIII activity actual/normal in Platelet poor plasma by Coagulation assay</span></a></td><td>145 %<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  code% = '%')</span></td><td>50 % - 150 %</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-antithrombin-iii-coag-panel.html\"><span title=\"Codes:{http://loinc.org 27811-9}\">Antithrombin actual/normal in Platelet poor plasma by Chromogenic method</span></a></td><td>92 %<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  code% = '%')</span></td><td>80 % - 120 %</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-protein-c-coag-panel.html\"><span title=\"Codes:{http://loinc.org 27820-0}\">Protein C Ag actual/normal in Platelet poor plasma by Immunoassay</span></a></td><td>88 %<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  code% = '%')</span></td><td>70 % - 130 %</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr><tr><td><a href=\"Observation-betsysmith-johnson01-obs-protein-s-coag-panel.html\"><span title=\"Codes:{http://loinc.org 27821-8}\">Protein S Free Ag actual/normal in Platelet poor plasma by Immunoassay</span></a></td><td>85 %<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  code% = '%')</span></td><td>60 % - 130 %</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td></tr></table><p>Coagulation profile shows evidence of acute thrombotic state with elevated fibrinogen and D-dimer, ongoing fibrinolysis following stroke, and hypercoagulable state typical in acute cerebrovascular events.</p></div>"
  },
  "status": "final",
  "category": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0074",
          "code": "LAB",
          "display": "Laboratory"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "57021-8",
        "display": "CBC W Auto Differential panel - Blood"
      }
    ],
    "text": "Coagulation Panel"
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "effectiveDateTime": "2025-05-03T08:30:00+11:00", "issued": "2025-05-03T08:30:00+11:00",
  "performer": [
    {
      "reference": "Organization/org-ED-Metro-Hospital"
    }
  ],
  "result": [
    {
      "reference": "Observation/betsysmith-johnson01-obs-pt-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-inr-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-aptt-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-ddimer-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-platelet-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-thrombin-time-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-factor-viii-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-antithrombin-iii-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-protein-c-coag-panel"
    },
    {
      "reference": "Observation/betsysmith-johnson01-obs-protein-s-coag-panel"
    }
  ],
  "conclusion": "Coagulation profile shows evidence of acute thrombotic state with elevated fibrinogen and D-dimer, ongoing fibrinolysis following stroke, and hypercoagulable state typical in acute cerebrovascular events."
}

=== node-on-fhir/core/packages/pacio-core/data/connectathon-july-2026-examples/DiagnosticReport-wilmamarina01-lipid-panel-01.json
{
  "resourceType": "DiagnosticReport",
  "id": "wilmamarina01-lipid-panel-01",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: DiagnosticReport wilmamarina01-lipid-panel-01</b></p><a name=\"wilmamarina01-lipid-panel-01\"> </a><a name=\"hcwilmamarina01-lipid-panel-01\"> </a><h2><span title=\"Codes:{http://loinc.org 57698-3}\">Lipid Panel</span> (<span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v2-0074 HM}\">Hematology</span>) </h2><table class=\"grid\"><tr><td>Subject</td><td>Marina, Wilma Female, DoB: 1950-11-15 ( http://hl7.org/fhir/sid/us-medicare#United States Medicare Number#1PA3D58WH17)</td></tr><tr><td>When For</td><td>2025-05-03 08:30:00+1100</td></tr><tr><td>Reported</td><td>2013-01-27 11:45:33+1100</td></tr><tr><td>Performer</td><td> <a href=\"Organization-org-PC-Primary-Care-Michigan.html\">Organization Michigan Primary Health Care Associates</a></td></tr><tr><td>Identifier</td><td> <code>http://example.org/lab/reports</code>/5234342</td></tr></table><p><b>Report Details</b></p><table class=\"grid\"><tr><td><b>Code</b></td><td><b>Value</b></td><td><b>Reference Range</b></td><td><b>Flags</b></td><td><b>Note</b></td></tr><tr><td><a href=\"Observation-wilmamarina01-observation-cholesterol-01.html\"><span title=\"Codes:{http://loinc.org 35200-5}\">Cholesterol [Mass or Moles/volume] in Serum or Plasma</span></a></td><td>6.3 mmol/L<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codemmol/L = 'mmol/L')</span></td><td>High Risk at or above 4.5 mmol/L (Per Australian NHF Recommendations)</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation H}\">High</span></td><td><blockquote><div><p>Patient reported having eaten fatty foods the day before.</p>\n</div></blockquote></td></tr><tr><td><a href=\"Observation-wilmamarina01-observation-triglyceride-01.html\"><span title=\"Codes:{http://loinc.org 35217-9}\">Triglyceride</span></a></td><td>1.3 mmol/L<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codemmol/L = 'mmol/L')</span></td><td>Normal range: less than 2.0 mmol/L</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation N}\">Normal</span></td><td/></tr><tr><td><a href=\"Observation-wilmamarina01-observation-hdl-01.html\"><span title=\"Codes:{http://loinc.org 2085-9}\">Cholesterol in HDL</span></a></td><td>1.3 mmol/L<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codemmol/L = 'mmol/L')</span></td><td>Desirable: greater than 1.5 mmol/L</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation L}\">Low</span></td><td/></tr><tr><td><a href=\"Observation-wilmamarina01-observation-ldl-01.html\"><span title=\"Codes:{http://loinc.org 13457-7}\">LDL Chol. (Calc)</span></a></td><td>4.6 mmol/L<span style=\"background: LightGoldenRodYellow\"> (Details: UCUM  codemmol/L = 'mmol/L')</span></td><td>Optimal: less than 3.0 mmol/L</td><td>Final, <span title=\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation H}\">High</span></td><td/></tr></table><p>Patient has elevated total cholesterol and LDL levels with borderline low HDL. Recommend lifestyle modifications and consideration of lipid-lowering therapy.</p></div>"
  },
  "identifier": [
    {
      "system": "http://example.org/lab/reports",
      "value": "5234342"
    }
  ],
  "status": "final",
  "category": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0074",
          "code": "HM",
          "display": "Hematology"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "57698-3",
        "display": "Lipid panel with direct LDL - Serum or Plasma"
      }
    ],
    "text": "Lipid Panel"
  },
  "subject": {
    "reference": "Patient/patient-wilmamarina01",
    "display": "Wilma Marina"
  },
  "effectiveDateTime": "2025-05-03T08:30:00+11:00",
  "issued": "2013-01-27T11:45:33+11:00",
  "performer": [
    {
      "reference": "Organization/org-PC-Primary-Care-Michigan"
    }
  ],
  "result": [
    {
      "reference": "Observation/wilmamarina01-observation-cholesterol-01"
    },
    {
      "reference": "Observation/wilmamarina01-observation-triglyceride-01"
    },
    {
      "reference": "Observation/wilmamarina01-observation-hdl-01"
    },
    {
      "reference": "Observation/wilmamarina01-observation-ldl-01"
    }
  ],
  "conclusion": "Patient has elevated total cholesterol and LDL levels with borderline low HDL. Recommend lifestyle modifications and consideration of lipid-lowering therapy."
}
