=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/MedicationRequest.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/MedicationRequest",
  "description": "An order or request for both supply of the medication and the instructions for administration of the medication to a patient.",
  "type": "object",
  "required": ["resourceType", "status", "intent", "subject"],
  "properties": {
    "resourceType": { "const": "MedicationRequest" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "status": { "type": "string", "enum": ["active", "on-hold", "cancelled", "completed", "entered-in-error", "stopped", "draft", "unknown"] },
    "statusReason": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "intent": { "type": "string", "enum": ["proposal", "plan", "order", "original-order", "reflex-order", "filler-order", "instance-order", "option"] },
    "category": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "priority": { "type": "string", "enum": ["routine", "urgent", "asap", "stat"] },
    "doNotPerform": { "type": "boolean" },
    "reportedBoolean": { "type": "boolean" },
    "reportedReference": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "medicationCodeableConcept": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "medicationReference": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "subject": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "encounter": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "supportingInformation": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "authoredOn": { "type": "string" },
    "requester": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "performer": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "performerType": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "recorder": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "reasonCode": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "reasonReference": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "instantiatesCanonical": { "type": "array", "items": { "type": "string" } },
    "instantiatesUri": { "type": "array", "items": { "type": "string" } },
    "basedOn": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "groupIdentifier": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } },
    "courseOfTherapyType": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } },
    "insurance": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "note": { "type": "array", "items": { "type": "object", "properties": { "text": { "type": "string" }, "time": { "type": "string" }, "authorReference": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } }, "authorString": { "type": "string" } } } },
    "dosageInstruction": { "type": "array", "items": { "type": "object", "properties": { "sequence": { "type": "integer" }, "text": { "type": "string" }, "additionalInstruction": { "type": "array", "items": { "type": "object" } }, "patientInstruction": { "type": "string" }, "timing": { "type": "object" }, "asNeededBoolean": { "type": "boolean" }, "asNeededCodeableConcept": { "type": "object" }, "site": { "type": "object" }, "route": { "type": "object" }, "method": { "type": "object" }, "doseAndRate": { "type": "array", "items": { "type": "object" } }, "maxDosePerPeriod": { "type": "object" }, "maxDosePerAdministration": { "type": "object" }, "maxDosePerLifetime": { "type": "object" } } } },
    "dispenseRequest": { "type": "object", "properties": { "initialFill": { "type": "object", "properties": { "quantity": { "type": "object" }, "duration": { "type": "object" } } }, "dispenseInterval": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" }, "system": { "type": "string" }, "code": { "type": "string" } } }, "validityPeriod": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } }, "numberOfRepeatsAllowed": { "type": "integer" }, "quantity": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" }, "system": { "type": "string" }, "code": { "type": "string" } } }, "expectedSupplyDuration": { "type": "object", "properties": { "value": { "type": "number" }, "unit": { "type": "string" }, "system": { "type": "string" }, "code": { "type": "string" } } }, "performer": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } } },
    "substitution": { "type": "object", "properties": { "allowedBoolean": { "type": "boolean" }, "allowedCodeableConcept": { "type": "object" }, "reason": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } } },
    "priorPrescription": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "detectedIssue": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "eventHistory": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/packages/pacio-core/data/connectathon-july-2026-examples/MedicationRequest-bsj1-smp-medrx-calcium-0-3.json
{
  "resourceType": "MedicationRequest",
  "id": "bsj1-smp-medrx-calcium-0-3",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: MedicationRequest bsj1-smp-medrx-calcium-0-3</b></p><a name=\"bsj1-smp-medrx-calcium-0-3\"> </a><a name=\"hcbsj1-smp-medrx-calcium-0-3\"> </a><p><b>status</b>: Stopped</p><p><b>intent</b>: Order</p><p><b>medication</b>: <span title=\"Codes:{http://www.nlm.nih.gov/research/umls/rxnorm 282465}, {http://hl7.org/fhir/sid/ndc 63629-2600-1}\">calcium carbonate 1250 MG Oral Tablet</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>authoredOn</b>: 2025-04-22 09:30:00-0800</p><p><b>requester</b>: <a href=\"PractitionerRole-Role-IMMD-AnitaChu.html\">PractitionerRole Primary care provider (occupation)</a></p></div>"
  },
  "status": "stopped",
  "intent": "order",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "282465",
        "display": "calcium carbonate 1250 MG Oral Tablet"
      },
      {
        "system": "http://hl7.org/fhir/sid/ndc",
        "code": "63629-2600-1"
      }
    ]
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "authoredOn": "2025-04-22T09:30:00-08:00",
  "requester": {
    "reference": "PractitionerRole/Role-IMMD-AnitaChu"
  }
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/MedicationRequest-bsj1-smp-medrx-lipitor-2-2.json
{
  "resourceType": "MedicationRequest",
  "id": "bsj1-smp-medrx-lipitor-2-2",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: MedicationRequest bsj1-smp-medrx-lipitor-2-2</b></p><a name=\"bsj1-smp-medrx-lipitor-2-2\"> </a><a name=\"hcbsj1-smp-medrx-lipitor-2-2\"> </a><p><b>status</b>: Active</p><p><b>intent</b>: Order</p><p><b>medication</b>: <span title=\"Codes:{http://www.nlm.nih.gov/research/umls/rxnorm 617320}, {http://hl7.org/fhir/sid/ndc 0071-0157-23}\">atorvastatin 40 MG Oral Tablet</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>authoredOn</b>: 2025-07-01 16:15:00-0800</p><p><b>requester</b>: <a href=\"PractitionerRole-PractitionerRole-MD-HemaOnko.html\">PractitionerRole Internal Medicine Physician</a></p></div>"
  },
  "status": "active",
  "intent": "order",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "617320",
        "display": "atorvastatin 40 MG Oral Tablet"
      },
      {
        "system": "http://hl7.org/fhir/sid/ndc",
        "code": "0071-0157-23"
      }
    ]
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "authoredOn": "2025-07-01T16:15:00-08:00",
  "requester": {
    "reference": "PractitionerRole/PractitionerRole-MD-HemaOnko"
  }
}

=== node-on-fhir/core/packages/pacio-core/data/connectathon-july-2026-examples/MedicationRequest-bsj1-smp-medrx-ferrous-4-3.json
{
  "resourceType": "MedicationRequest",
  "id": "bsj1-smp-medrx-ferrous-4-3",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: MedicationRequest bsj1-smp-medrx-ferrous-4-3</b></p><a name=\"bsj1-smp-medrx-ferrous-4-3\"> </a><a name=\"hcbsj1-smp-medrx-ferrous-4-3\"> </a><p><b>status</b>: Active</p><p><b>intent</b>: Order</p><p><b>medication</b>: <span title=\"Codes:{http://www.nlm.nih.gov/research/umls/rxnorm 702249}, {http://hl7.org/fhir/sid/ndc 0536-1400-85}\">ferrous sulfate 44 MG/ML Oral Solution</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>authoredOn</b>: 2025-07-16 11:30:00-0800</p><p><b>requester</b>: <a href=\"PractitionerRole-Role-IMMD-AnitaChu.html\">PractitionerRole Primary care provider (occupation)</a></p></div>"
  },
  "status": "active",
  "intent": "order",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "702249",
        "display": "ferrous sulfate 44 MG/ML Oral Solution"
      },
      {
        "system": "http://hl7.org/fhir/sid/ndc",
        "code": "0536-1400-85"
      }
    ]
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "authoredOn": "2025-07-16T11:30:00-08:00",
  "requester": {
    "reference": "PractitionerRole/Role-IMMD-AnitaChu"
  }
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/BetsySmithJohnson/MedicationRequest-bsj1-smp-medrx-insulin-2-11.json
{
  "resourceType": "MedicationRequest",
  "id": "bsj1-smp-medrx-insulin-2-11",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: MedicationRequest bsj1-smp-medrx-insulin-2-11</b></p><a name=\"bsj1-smp-medrx-insulin-2-11\"> </a><a name=\"hcbsj1-smp-medrx-insulin-2-11\"> </a><p><b>status</b>: Active</p><p><b>intent</b>: Order</p><p><b>medication</b>: <span title=\"Codes:{http://www.nlm.nih.gov/research/umls/rxnorm 311048}, {http://hl7.org/fhir/sid/ndc 71093-143-11}\">insulin isophane, human 70 UNT/ML / insulin, regular, human 30 UNT/ML Injectable Suspension</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>authoredOn</b>: 2025-07-02 13:00:00-0800</p><p><b>requester</b>: <a href=\"PractitionerRole-PractitionerRole-MD-HemaOnko.html\">PractitionerRole Internal Medicine Physician</a></p></div>"
  },
  "status": "active",
  "intent": "order",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "311048",
        "display": "insulin isophane, human 70 UNT/ML / insulin, regular, human 30 UNT/ML Injectable Suspension"
      },
      {
        "system": "http://hl7.org/fhir/sid/ndc",
        "code": "71093-143-11"
      }
    ]
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "authoredOn": "2025-07-02T13:00:00-08:00",
  "requester": {
    "reference": "PractitionerRole/PractitionerRole-MD-HemaOnko"
  }
}

=== node-on-fhir/core/npmPackages/pacio-core/data/2026-07-cms-connectathon/BetsySmithJohnson/fhir/MedicationRequest-bsj1-smp-medrx-sitagliptin-3-6.json
{
  "resourceType": "MedicationRequest",
  "id": "bsj1-smp-medrx-sitagliptin-3-6",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: MedicationRequest bsj1-smp-medrx-sitagliptin-3-6</b></p><a name=\"bsj1-smp-medrx-sitagliptin-3-6\"> </a><a name=\"hcbsj1-smp-medrx-sitagliptin-3-6\"> </a><p><b>status</b>: Active</p><p><b>intent</b>: Order</p><p><b>medication</b>: <span title=\"Codes:{http://www.nlm.nih.gov/research/umls/rxnorm 665042}, {http://hl7.org/fhir/sid/ndc 70710-1900-9}\">sitagliptin 50 MG Oral Tablet</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>authoredOn</b>: 2025-07-03 09:00:00-0800</p><p><b>requester</b>: <a href=\"PractitionerRole-PractitionerRole-DNP-JudySalas.html\">PractitionerRole Nurse Practitioner</a></p></div>"
  },
  "status": "active",
  "intent": "order",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "665042",
        "display": "sitagliptin 50 MG Oral Tablet"
      },
      {
        "system": "http://hl7.org/fhir/sid/ndc",
        "code": "70710-1900-9"
      }
    ]
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "authoredOn": "2025-07-03T09:00:00-08:00",
  "requester": {
    "reference": "PractitionerRole/PractitionerRole-DNP-JudySalas"
  }
}

=== node-on-fhir/core/packages/pacio-core/data/connectathon-july-2026-examples/MedicationRequest-bsj1-smp-medrx-sertraline-1-8.json
{
  "resourceType": "MedicationRequest",
  "id": "bsj1-smp-medrx-sertraline-1-8",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: MedicationRequest bsj1-smp-medrx-sertraline-1-8</b></p><a name=\"bsj1-smp-medrx-sertraline-1-8\"> </a><a name=\"hcbsj1-smp-medrx-sertraline-1-8\"> </a><p><b>status</b>: Active</p><p><b>intent</b>: Order</p><p><b>medication</b>: <span title=\"Codes:{http://www.nlm.nih.gov/research/umls/rxnorm 312940}, {http://hl7.org/fhir/sid/ndc 0143-9656-09}\">sertraline 25 MG Oral Tablet</span></p><p><b>subject</b>: <a href=\"Patient-patient-betsysmith-johnson01.html\">Betsy Smith-Johnson</a></p><p><b>authoredOn</b>: 2025-05-03 14:45:00-0800</p><p><b>requester</b>: <a href=\"PractitionerRole-PractitionerRole-Physician-PriyaSarkar.html\">PractitionerRole Emergency Medicine Physician</a></p></div>"
  },
  "status": "active",
  "intent": "order",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "312940",
        "display": "sertraline 25 MG Oral Tablet"
      },
      {
        "system": "http://hl7.org/fhir/sid/ndc",
        "code": "0143-9656-09"
      }
    ]
  },
  "subject": {
    "reference": "Patient/patient-betsysmith-johnson01",
    "display": "Betsy Smith-Johnson"
  },
  "authoredOn": "2025-05-03T14:45:00-08:00",
  "requester": {
    "reference": "PractitionerRole/PractitionerRole-Physician-PriyaSarkar"
  }
}
