=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/Organization.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/Organization",
  "description": "A formally or informally recognized grouping of people or organizations formed for the purpose of achieving some form of collective action. Includes companies, institutions, corporations, departments, community groups, healthcare practice groups, payer/insurer, etc.",
  "type": "object",
  "required": ["resourceType"],
  "properties": {
    "resourceType": { "const": "Organization" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "type": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } }, "system": { "type": "string" }, "value": { "type": "string" }, "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } }, "assigner": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } } } },
    "active": { "type": "boolean" },
    "type": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "name": { "type": "string" },
    "alias": { "type": "array", "items": { "type": "string" } },
    "telecom": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "value": { "type": "string" }, "use": { "type": "string" }, "rank": { "type": "integer" }, "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "address": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "type": { "type": "string" }, "text": { "type": "string" }, "line": { "type": "array", "items": { "type": "string" } }, "city": { "type": "string" }, "district": { "type": "string" }, "state": { "type": "string" }, "postalCode": { "type": "string" }, "country": { "type": "string" }, "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "partOf": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "contact": { "type": "array", "items": { "type": "object", "properties": { "purpose": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } }, "name": { "type": "object", "properties": { "use": { "type": "string" }, "text": { "type": "string" }, "family": { "type": "string" }, "given": { "type": "array", "items": { "type": "string" } }, "prefix": { "type": "array", "items": { "type": "string" } }, "suffix": { "type": "array", "items": { "type": "string" } } } }, "telecom": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "value": { "type": "string" }, "use": { "type": "string" } } } }, "address": { "type": "object", "properties": { "use": { "type": "string" }, "type": { "type": "string" }, "text": { "type": "string" }, "line": { "type": "array", "items": { "type": "string" } }, "city": { "type": "string" }, "district": { "type": "string" }, "state": { "type": "string" }, "postalCode": { "type": "string" }, "country": { "type": "string" } } } } } },
    "endpoint": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/packages/pacio-core/data/connectathon-july-2026-examples/Organization-org-Motor-City-Skilled-Nursing-Facility.json
{
  "resourceType": "Organization",
  "id": "org-Motor-City-Skilled-Nursing-Facility",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Organization org-Motor-City-Skilled-Nursing-Facility</b></p><a name=\"org-Motor-City-Skilled-Nursing-Facility\"> </a><a name=\"hcorg-Motor-City-Skilled-Nursing-Facility\"> </a><p><b>active</b>: true</p><p><b>name</b>: Motor City Skilled Nursing Facility</p><p><b>telecom</b>: ph: (313) 640-1000</p><p><b>address</b>: 18051 Mack Ave Detroit MI 48224 US </p><p><b>endpoint</b>: <a href=\"Endpoint-endpoint-Motor-City-Skilled-Nursing-Facility.html\">Endpoint: status = active; connectionType = HL7 FHIR (Endpoint Connection Type#hl7-fhir-rest); payloadType = Bundle; address = https://actualmeds.com/fhir</a></p></div>"
  },
  "active": true,
  "name": "Motor City Skilled Nursing Facility",
  "telecom": [
    {
      "system": "phone",
      "value": "(313) 640-1000"
    }
  ],
  "address": [
    {
      "line": [
        "18051 Mack Ave"
      ],
      "city": "Detroit",
      "state": "MI",
      "postalCode": "48224",
      "country": "US"
    }
  ],
  "endpoint": [
    {
      "reference": "Endpoint/endpoint-Motor-City-Skilled-Nursing-Facility"
    }
  ]
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/Organization-org-The-Vernon-Center.json
{
  "resourceType": "Organization",
  "id": "org-The-Vernon-Center",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Organization org-The-Vernon-Center</b></p><a name=\"org-The-Vernon-Center\"> </a><a name=\"hcorg-The-Vernon-Center\"> </a><p><b>active</b>: true</p><p><b>name</b>: The Vernon Center</p><p><b>telecom</b>: ph: (555) 347-8877</p><p><b>address</b>: 9341 Agnes Street Detroit MI 48214 US </p></div>"
  },
  "active": true,
  "name": "The Vernon Center",
  "telecom": [
    {
      "system": "phone",
      "value": "(555) 347-8877"
    }
  ],
  "address": [
    {
      "line": [
        "9341 Agnes Street"
      ],
      "city": "Detroit",
      "state": "MI",
      "postalCode": "48214",
      "country": "US"
    }
  ]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/Organizations/Organization-org-PC-Primary-Care-Michigan.json
{
  "resourceType": "Organization",
  "id": "org-PC-Primary-Care-Michigan",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: Organization org-PC-Primary-Care-Michigan</b></p><a name=\"org-PC-Primary-Care-Michigan\"> </a><a name=\"hcorg-PC-Primary-Care-Michigan\"> </a><p><b>active</b>: true</p><p><b>name</b>: Michigan Primary Health Care Associates</p><p><b>telecom</b>: ph: (616) 555-1212</p><p><b>address</b>: 123 Spruce Dr. Grand Rapids, MI 49503</p></div>"
  },
  "active": true,
  "name": "Michigan Primary Health Care Associates",
  "telecom": [
    {
      "system": "phone",
      "value": "(616) 555-1212"
    }
  ],
  "address": [
    {
      "text": "123 Spruce Dr. Grand Rapids, MI 49503",
      "line": [
        "123 Spruce Dr"
      ],
      "city": "Grand Rapids",
      "state": "MI",
      "postalCode": "49503",
      "country": "US"
    }
  ]
}
