=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/PractitionerRole.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/PractitionerRole",
  "description": "A specific set of Roles/Locations/specialties/services that a practitioner may perform at an organization for a period of time.",
  "type": "object",
  "required": ["resourceType"],
  "properties": {
    "resourceType": { "const": "PractitionerRole" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "active": { "type": "boolean" },
    "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "practitioner": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "organization": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "code": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "specialty": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "location": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "healthcareService": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "telecom": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "value": { "type": "string" }, "use": { "type": "string" }, "rank": { "type": "integer" }, "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "availableTime": { "type": "array", "items": { "type": "object", "properties": { "daysOfWeek": { "type": "array", "items": { "type": "string" } }, "allDay": { "type": "boolean" }, "availableStartTime": { "type": "string" }, "availableEndTime": { "type": "string" } } } },
    "notAvailable": { "type": "array", "items": { "type": "object", "properties": { "description": { "type": "string" }, "during": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "availabilityExceptions": { "type": "string" },
    "endpoint": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/Practitioners/PractitionerRole-Role-SNFDoc-GeraldPark.json
{
  "resourceType": "PractitionerRole",
  "id": "Role-SNFDoc-GeraldPark", "telecom": [{"system": "phone", "value": "(555) 566 3494"}, {"system": "email", "value": "gpark@patientcentricsolutions.com"}],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole Role-SNFDoc-GeraldPark</b></p><a name=\"Role-SNFDoc-GeraldPark\"> </a><a name=\"hcRole-SNFDoc-GeraldPark\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-GeraldPark.html\">Gerald Park</a></p><p><b>organization</b>: <a href=\"Organization-org-Motor-City-Skilled-Nursing-Facility.html\">Happy Nursing Facility</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 207QG0300X}\">Geriatric Medicine Physician</span></p><p><b>location</b>: <a href=\"Location-org-Loc-SNF-Happy-Nursing-Facility.html\">Location Happy Nursing Facility</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-GeraldPark",
    "display": "Gerald Park"
  },
  "organization": {
    "reference": "Organization/org-Motor-City-Skilled-Nursing-Facility",
    "display": "Happy Nursing Facility"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "207QG0300X",
          "display": "Geriatric Medicine (Family Medicine) Physician"
        }
      ],
      "text": "Geriatric Medicine Physician"
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-SNF-Happy-Nursing-Facility"
    }
  ]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/2025-01-hl7-connectathon/longitudinal/PractitionerRole-Role-IMMD-AnitaChu.json
{
  "resourceType": "PractitionerRole",
  "id": "Role-IMMD-AnitaChu", "telecom": [{"system": "phone", "value": "(555) 638-1212"}, {"system": "email", "value": "achu@MichiganPrimaryCare.com"}],
  "active": true,
  "code": [
    {
      "coding": [
        {
          "code": "207R00000X",
          "system": "https://taxonomy.nucc.org/",
          "display": "Internal Medicine Physician"
        }
      ]
    }
  ],
  "practitioner": {
    "reference": "Practitioner/Practitioner-AnitaChu",
    "display": "Dr. Anita Chu"
  },
  "organization": {
    "reference": "Organization/org-PC-Primary-Care-FederalWay",
    "display": "Washington Primary Health Care Associates"
  },
  "location": [
    {
      "reference": "Location/org-Loc-PC-Primary-Care-FederalWay"
    }
  ]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/Practitioners/PractitionerRole-PractitionerRole-RN-RichardRisto.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-RN-RichardRisto", "telecom": [{"system": "phone", "value": "(555) 346-8624"}, {"system": "email", "value": "rristo@MetroHospital.com"}],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-RN-RichardRisto</b></p><a name=\"PractitionerRole-RN-RichardRisto\"> </a><a name=\"hcPractitionerRole-RN-RichardRisto\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-RichardRisto.html\">Richard Risto</a></p><p><b>organization</b>: <a href=\"Organization-org-ED-Metro-Hospital.html\">Metro Hospital Emergency Department</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 163W00000X}\">Registered Nurse</span></p><p><b>location</b>: <a href=\"Location-org-Loc-ED-Metro-Hospital.html\">Location Metro Hospital Emergency Department</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-RichardRisto",
    "display": "Richard Risto"
  },
  "organization": {
    "reference": "Organization/org-ED-Metro-Hospital",
    "display": "Metro Hospital Emergency Department"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "163W00000X",
          "display": "Registered Nurse"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-ED-Metro-Hospital"
    }
  ]
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/PractitionerRole-PFEIG-Role-SLP-LunaBaskins.json
{
  "resourceType" : "PractitionerRole",
  "id" : "PFEIG-Role-SLP-LunaBaskins",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PFEIG-Role-SLP-LunaBaskins</b></p><a name=\"PFEIG-Role-SLP-LunaBaskins\"> </a><a name=\"hcPFEIG-Role-SLP-LunaBaskins\"> </a><a name=\"PFEIG-Role-SLP-LunaBaskins-en-US\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-PFEIG-Practitioner-LunaBaskins.html\">Practitioner Luna Baskins</a></p><p><b>organization</b>: <a href=\"Organization-PFEIG-Org-03.html\">Organization Sky Harbor Home Health Services</a></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 159026005}\">Speech and language therapist</span></p><p><b>location</b>: <a href=\"Location-PFEIG-Org-Loc-03.html\">Location Sky Harbor Home Health Services</a></p></div>"
  },
  "active" : true,
  "practitioner" : {
    "reference" : "Practitioner/PFEIG-Practitioner-LunaBaskins"
  },
  "organization" : {
    "reference" : "Organization/PFEIG-Org-03"
  },
  "code" : [{
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "159026005",
      "display" : "Speech and language therapist"
    }]
  }],
  "location" : [{
    "reference" : "Location/PFEIG-Org-Loc-03"
  }]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/Practitioners/PractitionerRole-PractitionerRole-MSW-MargaretReynolds.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-MSW-MargaretReynolds", "telecom": [{"system": "phone", "value": "(555) 391-9414"}, {"system": "email", "value": "Maria.moen21@jettelabs.com"}],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-MSW-MargaretReynolds</b></p><a name=\"PractitionerRole-MSW-MargaretReynolds\"> </a><a name=\"hcPractitionerRole-MSW-MargaretReynolds\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-MargaretReynolds.html\">Margaret A. Reynolds</a></p><p><b>organization</b>: <a href=\"Organization-org-Motor-City-Skilled-Nursing-Facility.html\">Motor City Skilled Nursing Facility</a></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 224598009}\">Trained social worker counselor (occupation)</span></p><p><b>location</b>: <a href=\"Location-org-Loc-Motor-City-Skilled-Nursing-Facility.html\">Location Motor City Nursing Facility</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-MargaretReynolds",
    "display": "Margaret A. Reynolds"
  },
  "organization": {
    "reference": "Organization/org-Motor-City-Skilled-Nursing-Facility",
    "display": "Motor City Skilled Nursing Facility"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "version": "http://snomed.info/sct/731000124108",
          "code": "224598009",
          "display": "Trained social worker counselor (occupation)"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-Motor-City-Skilled-Nursing-Facility"
    }
  ]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/Practitioners/PractitionerRole-PractitionerRole-Radiologist-PaulZawawi.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-Radiologist-PaulZawawi", "telecom": [{"system": "phone", "value": "(555) 663-9348"}, {"system": "email", "value": "pzawawi@MetroHospital.com"}],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-Radiologist-PaulZawawi</b></p><a name=\"PractitionerRole-Radiologist-PaulZawawi\"> </a><a name=\"hcPractitionerRole-Radiologist-PaulZawawi\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-PaulZawawi.html\">Paul Zawawi</a></p><p><b>organization</b>: <a href=\"Organization-org-ED-Metro-Hospital.html\">Metro Hospital Emergency Department</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 2085N0700X}\">Neuroradiology Physician</span></p><p><b>location</b>: <a href=\"Location-org-Loc-ED-Metro-Hospital.html\">Location Metro Hospital Emergency Department</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-PaulZawawi",
    "display": "Paul Zawawi"
  },
  "organization": {
    "reference": "Organization/org-ED-Metro-Hospital",
    "display": "Metro Hospital Emergency Department"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "2085N0700X",
          "display": "Neuroradiology Physician"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-ED-Metro-Hospital"
    }
  ]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/2025-01-hl7-connectathon/longitudinal/PractitionerRole-Role-Path-PeterPathologist.json
{
    "resourceType": "PractitionerRole",
    "id": "Role-Path-PeterPathologist", "telecom": [{"system": "phone", "value": "(206)-444-4433"}, {"system": "email", "value": "PPathologist@PudgetOnc.org"}],
    "active": true,
    "code": [
      {
        "coding": [
          {
            "code": "207ZC0500X",
            "system": "https://taxonomy.nucc.org/",
            "display": "Cytopathology Physician"
          }
        ]
      }
    ],
    "practitioner": {
      "reference": "Practitioner/Practitioner-PeterPathologist",
      "display": "Peter Pathologist"
    },
    "organization": {
      "reference": "Organization/Org-Onc-Hosp-Puget-Sound",
      "display": "Puget Sound Cancer Center"
    },
    "location": [
      {
        "reference": "Location/org-Loc-Hosp-Puget-Sound"
      }
    ]
  }

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/PractitionerRole-PractitionerRole-SLP-JoeBukoski.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-SLP-JoeBukoski",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-SLP-JoeBukoski</b></p><a name=\"PractitionerRole-SLP-JoeBukoski\"> </a><a name=\"hcPractitionerRole-SLP-JoeBukoski\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-JoeBukoski.html\">Joe Bukoski</a></p><p><b>organization</b>: <a href=\"Organization-org-Motor-City-Skilled-Nursing-Facility.html\">Motor City Skilled Nursing Facility</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 235Z00000X}\">Speech-Language Pathologist</span></p><p><b>location</b>: <a href=\"Location-org-Loc-Motor-City-Skilled-Nursing-Facility.html\">Location Motor City Nursing Facility</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-JoeBukoski",
    "display": "Joe Bukoski"
  },
  "organization": {
    "reference": "Organization/org-Motor-City-Skilled-Nursing-Facility",
    "display": "Motor City Skilled Nursing Facility"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "235Z00000X",
          "display": "Speech-Language Pathologist"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-Motor-City-Skilled-Nursing-Facility"
    }
  ]
}
