=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/PractitionerRole.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/PractitionerRole",
  "description": "A specific set of Roles/Locations/specialties/services that a practitioner may perform at an organization for a period of time.",
  "type": "object",
  "required": ["resourceType"],
  "properties": {
    "resourceType": { "const": "PractitionerRole" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "active": { "type": "boolean" },
    "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "practitioner": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "organization": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "code": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "specialty": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "location": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "healthcareService": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "telecom": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "value": { "type": "string" }, "use": { "type": "string" }, "rank": { "type": "integer" }, "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "availableTime": { "type": "array", "items": { "type": "object", "properties": { "daysOfWeek": { "type": "array", "items": { "type": "string" } }, "allDay": { "type": "boolean" }, "availableStartTime": { "type": "string" }, "availableEndTime": { "type": "string" } } } },
    "notAvailable": { "type": "array", "items": { "type": "object", "properties": { "description": { "type": "string" }, "during": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "availabilityExceptions": { "type": "string" },
    "endpoint": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/npmPackages/pacio-core/data/2025-01-hl7-connectathon/longitudinal/PractitionerRole-Role-SNFDoc-GeraldPark.json
{
  "resourceType": "PractitionerRole",
  "id": "Role-SNFDoc-GeraldPark", "telecom": [{"system": "phone", "value": "(555) 566 3494"}, {"system": "email", "value": "gpark@patientcentricsolutions.com"}],
  "active": true,
  "code": [
    {
      "coding": [
        {
          "code": "207QG0300X",
          "system": "https://taxonomy.nucc.org/",
          "display": "Geriatric Medicine Physician"
        }
      ]
    }
  ],
  "practitioner": {
    "reference": "Practitioner/Practitioner-GeraldPark",
    "display": "Gerald Park"
  },
  "organization": {
    "reference": "Organization/org-SNF-Happy-Nursing-Facility",
    "display": "Happy Nursing Facility"
  },
  "location": [
    {
      "reference": "Location/org-Loc-SNF-Happy-Nursing-Facility"
    }
  ]
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/PractitionerRole-PFEIG-Role-OT-DanielGranger.json
{
  "resourceType" : "PractitionerRole",
  "id" : "PFEIG-Role-OT-DanielGranger",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PFEIG-Role-OT-DanielGranger</b></p><a name=\"PFEIG-Role-OT-DanielGranger\"> </a><a name=\"hcPFEIG-Role-OT-DanielGranger\"> </a><a name=\"PFEIG-Role-OT-DanielGranger-en-US\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-PFEIG-Practitioner-DanielGranger.html\">Practitioner Daniel Granger</a></p><p><b>organization</b>: <a href=\"Organization-PFEIG-Org-02.html\">Organization Happy Nursing Facility</a></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 80546007}\">Occupational therapist</span></p><p><b>location</b>: <a href=\"Location-PFEIG-Org-Loc-02.html\">Location Happy Nursing Facility</a></p></div>"
  },
  "active" : true,
  "practitioner" : {
    "reference" : "Practitioner/PFEIG-Practitioner-DanielGranger"
  },
  "organization" : {
    "reference" : "Organization/PFEIG-Org-02"
  },
  "code" : [{
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "80546007",
      "display" : "Occupational therapist"
    }]
  }],
  "location" : [{
    "reference" : "Location/PFEIG-Org-Loc-02"
  }]
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/PractitionerRole-PractitionerRole-RN-NichelleLorna.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-RN-NichelleLorna",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-RN-NichelleLorna</b></p><a name=\"PractitionerRole-RN-NichelleLorna\"> </a><a name=\"hcPractitionerRole-RN-NichelleLorna\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-NichelleLorna.html\">Nichelle Lorna</a></p><p><b>organization</b>: <a href=\"Organization-org-Motown-Home-Health.html\">Motown Home Health Agency</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 163W00000X}\">Registered Nurse</span></p><p><b>location</b>: <a href=\"Location-org-Loc-Motown-Home-Health.html\">Location Motown Home Health</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-NichelleLorna",
    "display": "Nichelle Lorna"
  },
  "organization": {
    "reference": "Organization/org-Motown-Home-Health",
    "display": "Motown Home Health Agency"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "163W00000X",
          "display": "Registered Nurse"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-Motown-Home-Health"
    }
  ]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/Practitioners/PractitionerRole-PractitionerRole-DNP-JudySalas.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-DNP-JudySalas", "telecom": [{"system": "phone", "value": "(555) 944-2454"}, {"system": "email", "value": "jsalas@MotownHHA.com"}],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-DNP-JudySalas</b></p><a name=\"PractitionerRole-DNP-JudySalas\"> </a><a name=\"hcPractitionerRole-DNP-JudySalas\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-JudySalas.html\">Judy Salas</a></p><p><b>organization</b>: <a href=\"Organization-org-Motown-Home-Health.html\">Motown Home Health Agency</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 363L00000X}\">Nurse Practitioner</span></p><p><b>location</b>: <a href=\"Location-org-Loc-Motown-Home-Health.html\">Location Motown Home Health</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-JudySalas",
    "display": "Judy Salas"
  },
  "organization": {
    "reference": "Organization/org-Motown-Home-Health",
    "display": "Motown Home Health Agency"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "363L00000X",
          "display": "Nurse Practitioner"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-Motown-Home-Health"
    }
  ]
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/PractitionerRole-PFEIG-Role-SNFDoc-GeraldPark.json
{
  "resourceType" : "PractitionerRole",
  "id" : "PFEIG-Role-SNFDoc-GeraldPark",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PFEIG-Role-SNFDoc-GeraldPark</b></p><a name=\"PFEIG-Role-SNFDoc-GeraldPark\"> </a><a name=\"hcPFEIG-Role-SNFDoc-GeraldPark\"> </a><a name=\"PFEIG-Role-SNFDoc-GeraldPark-en-US\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-PFEIG-Practioner-GeraldPark.html\">Gerald Park</a></p><p><b>organization</b>: <a href=\"Organization-PFEIG-Org-02.html\">Happy Nursing Facility</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 207QG0300X}\">Geriatric Medicine (Family Medicine) Physician</span></p><p><b>location</b>: <a href=\"Location-PFEIG-Org-Loc-02.html\">Location Happy Nursing Facility</a></p></div>"
  },
  "active" : true,
  "practitioner" : {
    "reference" : "Practitioner/PFEIG-Practioner-GeraldPark",
    "display" : "Gerald Park"
  },
  "organization" : {
    "reference" : "Organization/PFEIG-Org-02",
    "display" : "Happy Nursing Facility"
  },
  "code" : [{
    "coding" : [{
      "system" : "http://nucc.org/provider-taxonomy",
      "code" : "207QG0300X",
      "display" : "Geriatric Medicine (Family Medicine) Physician"
    }]
  }],
  "location" : [{
    "reference" : "Location/PFEIG-Org-Loc-02"
  }]
}

=== node-on-fhir/core/npmPackages/pacio-core/data/2025-01-hl7-connectathon/longitudinal/PractitionerRole-Role-SLP-AlexanderKuikhoff.json
{
  "resourceType": "PractitionerRole",
  "id": "Role-SLP-AlexanderKuikhoff", "telecom": [{"system": "phone", "value": "(210) 555 1871"}, {"system": "email", "value": "akuikhoff@patientcentricsolutions.com"}],
  "active": true,
  "code": [
    {
      "coding": [
        {
          "code": "235Z00000X",
          "system": "https://taxonomy.nucc.org/",
          "display": "Speech Language Pathologist"
        }
      ]
    }
  ],
  "practitioner": {
    "reference": "Practitioner/Practitioner-AlexanderKuikhoff",
    "display": "Alexander Kuikhoff"
  },
  "organization": {
    "reference": "Organization/org-SNF-Happy-Nursing-Facility",
    "display": "Happy Nursing Facility"
  },
  "location": [
    {
      "reference": "Location/org-Loc-SNF-Happy-Nursing-Facility"
    }
  ]
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/PractitionerRole-PractitionerRole-Neuro-DavidAlbahari.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-Neuro-DavidAlbahari",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-Neuro-DavidAlbahari</b></p><a name=\"PractitionerRole-Neuro-DavidAlbahari\"> </a><a name=\"hcPractitionerRole-Neuro-DavidAlbahari\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-DavidAlbahari.html\">David Albahari</a></p><p><b>organization</b>: <a href=\"Organization-org-ED-Metro-Hospital.html\">Metro Hospital Emergency Department</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 2084N0400X}\">Neurology Physician</span></p><p><b>location</b>: <a href=\"Location-org-Loc-ED-Metro-Hospital.html\">Location Metro Hospital Emergency Department</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-DavidAlbahari",
    "display": "David Albahari"
  },
  "organization": {
    "reference": "Organization/org-ED-Metro-Hospital",
    "display": "Metro Hospital Emergency Department"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "2084N0400X",
          "display": "Neurology Physician"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-ED-Metro-Hospital"
    }
  ]
}

=== node-on-fhir/core/packages/pacio-core/data/PACIO-examples/PractitionerRole-PFEIG-Role-PT-SallySmith.json
{
  "resourceType" : "PractitionerRole",
  "id" : "PFEIG-Role-PT-SallySmith",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PFEIG-Role-PT-SallySmith</b></p><a name=\"PFEIG-Role-PT-SallySmith\"> </a><a name=\"hcPFEIG-Role-PT-SallySmith\"> </a><a name=\"PFEIG-Role-PT-SallySmith-en-US\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-PFEIG-Practitioner-SallySmith.html\">Practitioner Sally Smith</a></p><p><b>organization</b>: <a href=\"Organization-PFEIG-Org-01.html\">Organization San Antonio General Hospital</a></p><p><b>code</b>: <span title=\"Codes:{http://snomed.info/sct 36682004}\">Physiotherapist</span></p><p><b>location</b>: <a href=\"Location-PFEIG-Org-Loc-01.html\">Location San Antonio General Hospital</a></p></div>"
  },
  "active" : true,
  "practitioner" : {
    "reference" : "Practitioner/PFEIG-Practitioner-SallySmith"
  },
  "organization" : {
    "reference" : "Organization/PFEIG-Org-01"
  },
  "code" : [{
    "coding" : [{
      "system" : "http://snomed.info/sct",
      "code" : "36682004",
      "display" : "Physiotherapist"
    }]
  }],
  "location" : [{
    "reference" : "Location/PFEIG-Org-Loc-01"
  }]
}
