=== node-on-fhir/core/imports/lib/schemas/R4B/JsonSchema/PractitionerRole.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/PractitionerRole",
  "description": "A specific set of Roles/Locations/specialties/services that a practitioner may perform at an organization for a period of time.",
  "type": "object",
  "required": ["resourceType"],
  "properties": {
    "resourceType": { "const": "PractitionerRole" },
    "id": { "type": "string", "description": "Logical id of this artifact" },
    "_id": { "type": "string", "description": "MongoDB primary key" },
    "meta": { "type": "object", "properties": { "versionId": { "type": "string" }, "lastUpdated": { "type": "string" }, "source": { "type": "string" }, "profile": { "type": "array", "items": { "type": "string" } }, "security": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "tag": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } } } },
    "implicitRules": { "type": "string" },
    "language": { "type": "string" },
    "text": { "type": "object", "properties": { "status": { "type": "string" }, "div": { "type": "string" } } },
    "contained": { "type": "array", "items": { "type": "object" } },
    "extension": { "type": "array", "items": { "type": "object" } },
    "modifierExtension": { "type": "array", "items": { "type": "object" } },
    "identifier": { "type": "array", "items": { "type": "object", "properties": { "use": { "type": "string" }, "system": { "type": "string" }, "value": { "type": "string" } } } },
    "active": { "type": "boolean" },
    "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } },
    "practitioner": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "organization": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } },
    "code": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "specialty": { "type": "array", "items": { "type": "object", "properties": { "coding": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "code": { "type": "string" }, "display": { "type": "string" } } } }, "text": { "type": "string" } } } },
    "location": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "healthcareService": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } },
    "telecom": { "type": "array", "items": { "type": "object", "properties": { "system": { "type": "string" }, "value": { "type": "string" }, "use": { "type": "string" }, "rank": { "type": "integer" }, "period": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "availableTime": { "type": "array", "items": { "type": "object", "properties": { "daysOfWeek": { "type": "array", "items": { "type": "string" } }, "allDay": { "type": "boolean" }, "availableStartTime": { "type": "string" }, "availableEndTime": { "type": "string" } } } },
    "notAvailable": { "type": "array", "items": { "type": "object", "properties": { "description": { "type": "string" }, "during": { "type": "object", "properties": { "start": { "type": "string" }, "end": { "type": "string" } } } } } },
    "availabilityExceptions": { "type": "string" },
    "endpoint": { "type": "array", "items": { "type": "object", "properties": { "reference": { "type": "string" }, "display": { "type": "string" } } } }
  }
}

=== node-on-fhir/core/npmPackages/pacio-core/data/connectathon-july-2026-examples/Practitioners/PractitionerRole-PractitionerRole-OT-InaKrause.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-OT-InaKrause", "telecom": [{"system": "phone", "value": "(555) 624-3552"}, {"system": "email", "value": "ikrause@MotownHHA.com"}],
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-OT-InaKrause</b></p><a name=\"PractitionerRole-OT-InaKrause\"> </a><a name=\"hcPractitionerRole-OT-InaKrause\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-InaKrause.html\">Ina Krause</a></p><p><b>organization</b>: <a href=\"Organization-org-Motown-Home-Health.html\">Motown Home Health Agency</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 225X00000X}\">Occupational Therapist</span></p><p><b>location</b>: <a href=\"Location-org-Loc-Motown-Home-Health.html\">Location Motown Home Health</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-InaKrause",
    "display": "Ina Krause"
  },
  "organization": {
    "reference": "Organization/org-Motown-Home-Health",
    "display": "Motown Home Health Agency"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "225X00000X",
          "display": "Occupational Therapist"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-Motown-Home-Health"
    }
  ]
}

=== node-on-fhir/core/deprecated/pacio-core/data/connectathon-july-2026-examples/PractitionerRole-PractitionerRole-PT-DeyonteDarden.json
{
  "resourceType": "PractitionerRole",
  "id": "PractitionerRole-PT-DeyonteDarden",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p class=\"res-header-id\"><b>Generated Narrative: PractitionerRole PractitionerRole-PT-DeyonteDarden</b></p><a name=\"PractitionerRole-PT-DeyonteDarden\"> </a><a name=\"hcPractitionerRole-PT-DeyonteDarden\"> </a><p><b>active</b>: true</p><p><b>practitioner</b>: <a href=\"Practitioner-Practitioner-DeyonteDarden.html\">Deyonte Darden</a></p><p><b>organization</b>: <a href=\"Organization-org-Motor-City-Skilled-Nursing-Facility.html\">Motor City Skilled Nursing Facility</a></p><p><b>code</b>: <span title=\"Codes:{http://nucc.org/provider-taxonomy 225100000X}\">Physical Therapist</span></p><p><b>location</b>: <a href=\"Location-org-Loc-Motor-City-Skilled-Nursing-Facility.html\">Location Motor City Nursing Facility</a></p></div>"
  },
  "active": true,
  "practitioner": {
    "reference": "Practitioner/Practitioner-DeyonteDarden",
    "display": "Deyonte Darden"
  },
  "organization": {
    "reference": "Organization/org-Motor-City-Skilled-Nursing-Facility",
    "display": "Motor City Skilled Nursing Facility"
  },
  "code": [
    {
      "coding": [
        {
          "system": "http://nucc.org/provider-taxonomy",
          "code": "225100000X",
          "display": "Physical Therapist"
        }
      ]
    }
  ],
  "location": [
    {
      "reference": "Location/org-Loc-Motor-City-Skilled-Nursing-Facility"
    }
  ]
}
